//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalWs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkOrderMasterModel", Namespace="http://schemas.datacontract.org/2004/07/Sparks.WcfService.DataContracts")]
    internal partial class WorkOrderMasterModel : object
    {
        
        private System.Collections.Generic.List<LocalWs.InvoiceModel> InvoiceListField;
        
        private System.Guid WorkOrderMasterIdField;
        
        private string WorkOrderNoField;
        
        private string DeclarationTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<LocalWs.InvoiceModel> InvoiceList
        {
            get
            {
                return this.InvoiceListField;
            }
            set
            {
                this.InvoiceListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid WorkOrderMasterId
        {
            get
            {
                return this.WorkOrderMasterIdField;
            }
            set
            {
                this.WorkOrderMasterIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string WorkOrderNo
        {
            get
            {
                return this.WorkOrderNoField;
            }
            set
            {
                this.WorkOrderNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        internal string DeclarationType
        {
            get
            {
                return this.DeclarationTypeField;
            }
            set
            {
                this.DeclarationTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceModel", Namespace="http://schemas.datacontract.org/2004/07/Sparks.WcfService.DataContracts")]
    internal partial class InvoiceModel : object
    {
        
        private System.Guid InvoiceIdField;
        
        private System.Guid WorkOrderMasterIdField;
        
        private string SenderNoField;
        
        private string SenderNameField;
        
        private string SenderAddressField;
        
        private string SenderCityField;
        
        private string SenderCountryField;
        
        private string ConsgnNameField;
        
        private string ConsgnAddressField;
        
        private string ConsgnCityField;
        
        private string ConsgnCountryField;
        
        private string TransptrNameField;
        
        private string VesselNameField;
        
        private string AgentNameField;
        
        private string PlateNoField;
        
        private string AwbNoField;
        
        private string BLNoField;
        
        private string IncotermsField;
        
        private string DeliveryLocationField;
        
        private decimal InvoiceAmountField;
        
        private string CustomsField;
        
        private string InvoiceCurrencyField;
        
        private System.Nullable<decimal> FreightAmountField;
        
        private string FreightCurrencyField;
        
        private System.Nullable<decimal> InsuranceAmountField;
        
        private string InsuranceCurrencyField;
        
        private string ConsgnNoField;
        
        private string ContainerNoField;
        
        private string GtbReferenceNoField;
        
        private string PaymentMethodField;
        
        private string EntryExitCustomsField;
        
        private System.Collections.Generic.List<LocalWs.InvoiceDetailModel> InvoiceDetailListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid InvoiceId
        {
            get
            {
                return this.InvoiceIdField;
            }
            set
            {
                this.InvoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid WorkOrderMasterId
        {
            get
            {
                return this.WorkOrderMasterIdField;
            }
            set
            {
                this.WorkOrderMasterIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        internal string SenderNo
        {
            get
            {
                return this.SenderNoField;
            }
            set
            {
                this.SenderNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        internal string SenderName
        {
            get
            {
                return this.SenderNameField;
            }
            set
            {
                this.SenderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        internal string SenderAddress
        {
            get
            {
                return this.SenderAddressField;
            }
            set
            {
                this.SenderAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        internal string SenderCity
        {
            get
            {
                return this.SenderCityField;
            }
            set
            {
                this.SenderCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        internal string SenderCountry
        {
            get
            {
                return this.SenderCountryField;
            }
            set
            {
                this.SenderCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        internal string ConsgnName
        {
            get
            {
                return this.ConsgnNameField;
            }
            set
            {
                this.ConsgnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        internal string ConsgnAddress
        {
            get
            {
                return this.ConsgnAddressField;
            }
            set
            {
                this.ConsgnAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        internal string ConsgnCity
        {
            get
            {
                return this.ConsgnCityField;
            }
            set
            {
                this.ConsgnCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        internal string ConsgnCountry
        {
            get
            {
                return this.ConsgnCountryField;
            }
            set
            {
                this.ConsgnCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        internal string TransptrName
        {
            get
            {
                return this.TransptrNameField;
            }
            set
            {
                this.TransptrNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        internal string VesselName
        {
            get
            {
                return this.VesselNameField;
            }
            set
            {
                this.VesselNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        internal string AgentName
        {
            get
            {
                return this.AgentNameField;
            }
            set
            {
                this.AgentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        internal string PlateNo
        {
            get
            {
                return this.PlateNoField;
            }
            set
            {
                this.PlateNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        internal string AwbNo
        {
            get
            {
                return this.AwbNoField;
            }
            set
            {
                this.AwbNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        internal string BLNo
        {
            get
            {
                return this.BLNoField;
            }
            set
            {
                this.BLNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        internal string Incoterms
        {
            get
            {
                return this.IncotermsField;
            }
            set
            {
                this.IncotermsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        internal string DeliveryLocation
        {
            get
            {
                return this.DeliveryLocationField;
            }
            set
            {
                this.DeliveryLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        internal decimal InvoiceAmount
        {
            get
            {
                return this.InvoiceAmountField;
            }
            set
            {
                this.InvoiceAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        internal string Customs
        {
            get
            {
                return this.CustomsField;
            }
            set
            {
                this.CustomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        internal string InvoiceCurrency
        {
            get
            {
                return this.InvoiceCurrencyField;
            }
            set
            {
                this.InvoiceCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        internal System.Nullable<decimal> FreightAmount
        {
            get
            {
                return this.FreightAmountField;
            }
            set
            {
                this.FreightAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        internal string FreightCurrency
        {
            get
            {
                return this.FreightCurrencyField;
            }
            set
            {
                this.FreightCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        internal System.Nullable<decimal> InsuranceAmount
        {
            get
            {
                return this.InsuranceAmountField;
            }
            set
            {
                this.InsuranceAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        internal string InsuranceCurrency
        {
            get
            {
                return this.InsuranceCurrencyField;
            }
            set
            {
                this.InsuranceCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        internal string ConsgnNo
        {
            get
            {
                return this.ConsgnNoField;
            }
            set
            {
                this.ConsgnNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        internal string ContainerNo
        {
            get
            {
                return this.ContainerNoField;
            }
            set
            {
                this.ContainerNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        internal string GtbReferenceNo
        {
            get
            {
                return this.GtbReferenceNoField;
            }
            set
            {
                this.GtbReferenceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        internal string PaymentMethod
        {
            get
            {
                return this.PaymentMethodField;
            }
            set
            {
                this.PaymentMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        internal string EntryExitCustoms
        {
            get
            {
                return this.EntryExitCustomsField;
            }
            set
            {
                this.EntryExitCustomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        internal System.Collections.Generic.List<LocalWs.InvoiceDetailModel> InvoiceDetailList
        {
            get
            {
                return this.InvoiceDetailListField;
            }
            set
            {
                this.InvoiceDetailListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceDetailModel", Namespace="http://schemas.datacontract.org/2004/07/Sparks.WcfService.DataContracts")]
    internal partial class InvoiceDetailModel : object
    {
        
        private System.Guid InvoiceDetailIdField;
        
        private System.Guid InvoiceIdField;
        
        private string HsCodeField;
        
        private string DescGoodsField;
        
        private string ProductNoField;
        
        private string CountryOfOriginField;
        
        private string UomField;
        
        private double ActualQuantityField;
        
        private double InvoiceQuantityField;
        
        private System.Nullable<double> GrossWeightField;
        
        private double NetWeightField;
        
        private string IntrnlAgmtField;
        
        private string InvoiceNoField;
        
        private System.DateTime InvoiceDateField;
        
        private double InvoiceAmountField;
        
        private string PkgTypeField;
        
        private string CommclDescField;
        
        private int NumberOfPackagesField;
        
        private int ItemNumberField;
        
        private string ProducerCompanyNoField;
        
        private string ProducerCompanyField;
        
        private string IncentiveLineNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid InvoiceDetailId
        {
            get
            {
                return this.InvoiceDetailIdField;
            }
            set
            {
                this.InvoiceDetailIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid InvoiceId
        {
            get
            {
                return this.InvoiceIdField;
            }
            set
            {
                this.InvoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        internal string HsCode
        {
            get
            {
                return this.HsCodeField;
            }
            set
            {
                this.HsCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        internal string DescGoods
        {
            get
            {
                return this.DescGoodsField;
            }
            set
            {
                this.DescGoodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        internal string ProductNo
        {
            get
            {
                return this.ProductNoField;
            }
            set
            {
                this.ProductNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        internal string CountryOfOrigin
        {
            get
            {
                return this.CountryOfOriginField;
            }
            set
            {
                this.CountryOfOriginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        internal string Uom
        {
            get
            {
                return this.UomField;
            }
            set
            {
                this.UomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        internal double ActualQuantity
        {
            get
            {
                return this.ActualQuantityField;
            }
            set
            {
                this.ActualQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        internal double InvoiceQuantity
        {
            get
            {
                return this.InvoiceQuantityField;
            }
            set
            {
                this.InvoiceQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        internal System.Nullable<double> GrossWeight
        {
            get
            {
                return this.GrossWeightField;
            }
            set
            {
                this.GrossWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        internal double NetWeight
        {
            get
            {
                return this.NetWeightField;
            }
            set
            {
                this.NetWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        internal string IntrnlAgmt
        {
            get
            {
                return this.IntrnlAgmtField;
            }
            set
            {
                this.IntrnlAgmtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        internal string InvoiceNo
        {
            get
            {
                return this.InvoiceNoField;
            }
            set
            {
                this.InvoiceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        internal System.DateTime InvoiceDate
        {
            get
            {
                return this.InvoiceDateField;
            }
            set
            {
                this.InvoiceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        internal double InvoiceAmount
        {
            get
            {
                return this.InvoiceAmountField;
            }
            set
            {
                this.InvoiceAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        internal string PkgType
        {
            get
            {
                return this.PkgTypeField;
            }
            set
            {
                this.PkgTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        internal string CommclDesc
        {
            get
            {
                return this.CommclDescField;
            }
            set
            {
                this.CommclDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        internal int NumberOfPackages
        {
            get
            {
                return this.NumberOfPackagesField;
            }
            set
            {
                this.NumberOfPackagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        internal int ItemNumber
        {
            get
            {
                return this.ItemNumberField;
            }
            set
            {
                this.ItemNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        internal string ProducerCompanyNo
        {
            get
            {
                return this.ProducerCompanyNoField;
            }
            set
            {
                this.ProducerCompanyNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        internal string ProducerCompany
        {
            get
            {
                return this.ProducerCompanyField;
            }
            set
            {
                this.ProducerCompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        internal string IncentiveLineNo
        {
            get
            {
                return this.IncentiveLineNoField;
            }
            set
            {
                this.IncentiveLineNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultModel", Namespace="http://schemas.datacontract.org/2004/07/Sparks.WcfService.DataContracts")]
    internal partial class ResultModel : object
    {
        
        private int ResultCodeField;
        
        private string ResultNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int ResultCode
        {
            get
            {
                return this.ResultCodeField;
            }
            set
            {
                this.ResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ResultName
        {
            get
            {
                return this.ResultNameField;
            }
            set
            {
                this.ResultNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsBeyannameModel", Namespace="http://schemas.datacontract.org/2004/07/Sparks.WcfService.DataContracts")]
    internal partial class WsBeyannameModel : object
    {
        
        private string AliciAdField;
        
        private string AliciAdresField;
        
        private string AliciNoField;
        
        private string AliciSehirField;
        
        private string AliciUlkeField;
        
        private string CikisVasitasiField;
        
        private string DosyaNoField;
        
        private string FaturaDovizKoduField;
        
        private string FaturaNoField;
        
        private decimal FaturaTutariField;
        
        private string GirisCikisGumrukField;
        
        private string GondericiAdField;
        
        private string GondericiAdresField;
        
        private string GondericiNoField;
        
        private string GondericiSehirField;
        
        private string GondericiUlkeField;
        
        private string GumrukField;
        
        private System.Nullable<System.DateTime> IntacTarihiField;
        
        private string MusRefNoField;
        
        private string NakliyeciField;
        
        private string NavlunDovizKoduField;
        
        private decimal NavlunTutariField;
        
        private string OdemeSekliField;
        
        private string RejimField;
        
        private string SigortaDovizKoduField;
        
        private decimal SigortaTutariField;
        
        private string SinirGecenVasitaField;
        
        private string TescilNoField;
        
        private System.Nullable<System.DateTime> TescilTarihiField;
        
        private string TeslimSekliField;
        
        private string TeslimYeriField;
        
        private System.Collections.Generic.List<LocalWs.WsBeyannameKalemModel> WsBeyannameKalemListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AliciAd
        {
            get
            {
                return this.AliciAdField;
            }
            set
            {
                this.AliciAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AliciAdres
        {
            get
            {
                return this.AliciAdresField;
            }
            set
            {
                this.AliciAdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AliciNo
        {
            get
            {
                return this.AliciNoField;
            }
            set
            {
                this.AliciNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AliciSehir
        {
            get
            {
                return this.AliciSehirField;
            }
            set
            {
                this.AliciSehirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AliciUlke
        {
            get
            {
                return this.AliciUlkeField;
            }
            set
            {
                this.AliciUlkeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CikisVasitasi
        {
            get
            {
                return this.CikisVasitasiField;
            }
            set
            {
                this.CikisVasitasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DosyaNo
        {
            get
            {
                return this.DosyaNoField;
            }
            set
            {
                this.DosyaNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FaturaDovizKodu
        {
            get
            {
                return this.FaturaDovizKoduField;
            }
            set
            {
                this.FaturaDovizKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FaturaNo
        {
            get
            {
                return this.FaturaNoField;
            }
            set
            {
                this.FaturaNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal FaturaTutari
        {
            get
            {
                return this.FaturaTutariField;
            }
            set
            {
                this.FaturaTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GirisCikisGumruk
        {
            get
            {
                return this.GirisCikisGumrukField;
            }
            set
            {
                this.GirisCikisGumrukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GondericiAd
        {
            get
            {
                return this.GondericiAdField;
            }
            set
            {
                this.GondericiAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GondericiAdres
        {
            get
            {
                return this.GondericiAdresField;
            }
            set
            {
                this.GondericiAdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GondericiNo
        {
            get
            {
                return this.GondericiNoField;
            }
            set
            {
                this.GondericiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GondericiSehir
        {
            get
            {
                return this.GondericiSehirField;
            }
            set
            {
                this.GondericiSehirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GondericiUlke
        {
            get
            {
                return this.GondericiUlkeField;
            }
            set
            {
                this.GondericiUlkeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Gumruk
        {
            get
            {
                return this.GumrukField;
            }
            set
            {
                this.GumrukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> IntacTarihi
        {
            get
            {
                return this.IntacTarihiField;
            }
            set
            {
                this.IntacTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string MusRefNo
        {
            get
            {
                return this.MusRefNoField;
            }
            set
            {
                this.MusRefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Nakliyeci
        {
            get
            {
                return this.NakliyeciField;
            }
            set
            {
                this.NakliyeciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string NavlunDovizKodu
        {
            get
            {
                return this.NavlunDovizKoduField;
            }
            set
            {
                this.NavlunDovizKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal NavlunTutari
        {
            get
            {
                return this.NavlunTutariField;
            }
            set
            {
                this.NavlunTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string OdemeSekli
        {
            get
            {
                return this.OdemeSekliField;
            }
            set
            {
                this.OdemeSekliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Rejim
        {
            get
            {
                return this.RejimField;
            }
            set
            {
                this.RejimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SigortaDovizKodu
        {
            get
            {
                return this.SigortaDovizKoduField;
            }
            set
            {
                this.SigortaDovizKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal SigortaTutari
        {
            get
            {
                return this.SigortaTutariField;
            }
            set
            {
                this.SigortaTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SinirGecenVasita
        {
            get
            {
                return this.SinirGecenVasitaField;
            }
            set
            {
                this.SinirGecenVasitaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TescilNo
        {
            get
            {
                return this.TescilNoField;
            }
            set
            {
                this.TescilNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> TescilTarihi
        {
            get
            {
                return this.TescilTarihiField;
            }
            set
            {
                this.TescilTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TeslimSekli
        {
            get
            {
                return this.TeslimSekliField;
            }
            set
            {
                this.TeslimSekliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TeslimYeri
        {
            get
            {
                return this.TeslimYeriField;
            }
            set
            {
                this.TeslimYeriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<LocalWs.WsBeyannameKalemModel> WsBeyannameKalemList
        {
            get
            {
                return this.WsBeyannameKalemListField;
            }
            set
            {
                this.WsBeyannameKalemListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsBeyannameKalemModel", Namespace="http://schemas.datacontract.org/2004/07/Sparks.WcfService.DataContracts")]
    internal partial class WsBeyannameKalemModel : object
    {
        
        private string BirimField;
        
        private System.Nullable<double> BrutKGField;
        
        private System.Nullable<double> CifTutarField;
        
        private System.Nullable<double> FobTutarField;
        
        private string GtipField;
        
        private System.Nullable<int> KalemNoField;
        
        private decimal KalemTutarField;
        
        private string KapField;
        
        private string KapCinsiField;
        
        private string MenseiUlkeField;
        
        private System.Nullable<decimal> MiktarField;
        
        private System.Nullable<double> NetKGField;
        
        private string RejimField;
        
        private string TesvikKalemNoField;
        
        private string TicariTanimField;
        
        private System.Collections.Generic.List<LocalWs.WsBeyannameKalemBelgeModel> WsBeyannameKalemBelgeListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Birim
        {
            get
            {
                return this.BirimField;
            }
            set
            {
                this.BirimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<double> BrutKG
        {
            get
            {
                return this.BrutKGField;
            }
            set
            {
                this.BrutKGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<double> CifTutar
        {
            get
            {
                return this.CifTutarField;
            }
            set
            {
                this.CifTutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<double> FobTutar
        {
            get
            {
                return this.FobTutarField;
            }
            set
            {
                this.FobTutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Gtip
        {
            get
            {
                return this.GtipField;
            }
            set
            {
                this.GtipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> KalemNo
        {
            get
            {
                return this.KalemNoField;
            }
            set
            {
                this.KalemNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal KalemTutar
        {
            get
            {
                return this.KalemTutarField;
            }
            set
            {
                this.KalemTutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Kap
        {
            get
            {
                return this.KapField;
            }
            set
            {
                this.KapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string KapCinsi
        {
            get
            {
                return this.KapCinsiField;
            }
            set
            {
                this.KapCinsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string MenseiUlke
        {
            get
            {
                return this.MenseiUlkeField;
            }
            set
            {
                this.MenseiUlkeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<decimal> Miktar
        {
            get
            {
                return this.MiktarField;
            }
            set
            {
                this.MiktarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<double> NetKG
        {
            get
            {
                return this.NetKGField;
            }
            set
            {
                this.NetKGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Rejim
        {
            get
            {
                return this.RejimField;
            }
            set
            {
                this.RejimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TesvikKalemNo
        {
            get
            {
                return this.TesvikKalemNoField;
            }
            set
            {
                this.TesvikKalemNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TicariTanim
        {
            get
            {
                return this.TicariTanimField;
            }
            set
            {
                this.TicariTanimField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<LocalWs.WsBeyannameKalemBelgeModel> WsBeyannameKalemBelgeList
        {
            get
            {
                return this.WsBeyannameKalemBelgeListField;
            }
            set
            {
                this.WsBeyannameKalemBelgeListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsBeyannameKalemBelgeModel", Namespace="http://schemas.datacontract.org/2004/07/Sparks.WcfService.DataContracts")]
    internal partial class WsBeyannameKalemBelgeModel : object
    {
        
        private int KalemNoField;
        
        private string KoduField;
        
        private string AciklamaField;
        
        private string DogrulamaField;
        
        private string ReferansField;
        
        private System.Nullable<System.DateTime> BelgeTarihiField;
        
        private System.Nullable<System.DateTime> VizeTarihiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int KalemNo
        {
            get
            {
                return this.KalemNoField;
            }
            set
            {
                this.KalemNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Kodu
        {
            get
            {
                return this.KoduField;
            }
            set
            {
                this.KoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        internal string Aciklama
        {
            get
            {
                return this.AciklamaField;
            }
            set
            {
                this.AciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        internal string Dogrulama
        {
            get
            {
                return this.DogrulamaField;
            }
            set
            {
                this.DogrulamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        internal string Referans
        {
            get
            {
                return this.ReferansField;
            }
            set
            {
                this.ReferansField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        internal System.Nullable<System.DateTime> BelgeTarihi
        {
            get
            {
                return this.BelgeTarihiField;
            }
            set
            {
                this.BelgeTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        internal System.Nullable<System.DateTime> VizeTarihi
        {
            get
            {
                return this.VizeTarihiField;
            }
            set
            {
                this.VizeTarihiField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalWs.IService1")]
    internal interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetWorkOrderMastersModel", ReplyAction="http://tempuri.org/IService1/SetWorkOrderMastersModelResponse")]
        System.Threading.Tasks.Task<LocalWs.ResultModel> SetWorkOrderMastersModelAsync(string UserNameWs, string PasswordWs, LocalWs.WorkOrderMasterModel workOrderMaster);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWorkOrderMastersModel", ReplyAction="http://tempuri.org/IService1/GetWorkOrderMastersModelResponse")]
        System.Threading.Tasks.Task<LocalWs.WorkOrderMasterModel> GetWorkOrderMastersModelAsync(string UserNameWs, string PasswordWs, string WorkOrderNo, string DeclarationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBeyannameModel", ReplyAction="http://tempuri.org/IService1/GetBeyannameModelResponse")]
        System.Threading.Tasks.Task<LocalWs.WsBeyannameModel> GetBeyannameModelAsync(string UserNameWs, string PasswordWs, string InvoiceNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface IService1Channel : LocalWs.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class Service1Client : System.ServiceModel.ClientBase<LocalWs.IService1>, LocalWs.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LocalWs.ResultModel> SetWorkOrderMastersModelAsync(string UserNameWs, string PasswordWs, LocalWs.WorkOrderMasterModel workOrderMaster)
        {
            return base.Channel.SetWorkOrderMastersModelAsync(UserNameWs, PasswordWs, workOrderMaster);
        }
        
        public System.Threading.Tasks.Task<LocalWs.WorkOrderMasterModel> GetWorkOrderMastersModelAsync(string UserNameWs, string PasswordWs, string WorkOrderNo, string DeclarationType)
        {
            return base.Channel.GetWorkOrderMastersModelAsync(UserNameWs, PasswordWs, WorkOrderNo, DeclarationType);
        }
        
        public System.Threading.Tasks.Task<LocalWs.WsBeyannameModel> GetBeyannameModelAsync(string UserNameWs, string PasswordWs, string InvoiceNo)
        {
            return base.Channel.GetBeyannameModelAsync(UserNameWs, PasswordWs, InvoiceNo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50241/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
