CREATE TABLE [dbo].[ChepStokGirisAktarim] (
    [ChepStokGirisAktarimId] INT             IDENTITY (1, 1) NOT NULL,
    [TpsNo]                  NVARCHAR (30)   NOT NULL,
    [TpsDurum]               NVARCHAR (50)   NULL,
    [BasvuruTarihi]          DATETIME        NULL,
    [SureSonuTarihi]         DATETIME        NULL,
    [GumrukKod]              NVARCHAR (6)    NULL,
    [BelgeAd]                NVARCHAR (50)   NULL,
    [BelgeSart]              NVARCHAR (50)   NULL,
    [TpsAciklama]            NVARCHAR (250)  NULL,
    [IthalatciFirma]         NVARCHAR (50)   NULL,
    [IhracatciFirma]         NVARCHAR (50)   NULL,
    [KapAdet]                INT             NULL,
    [TpsSiraNo]              INT             NULL,
    [TpsCikisSiraNo]         INT             NULL,
    [BeyannameKalemNo]       INT             NULL,
    [TpsBeyan]               NVARCHAR (20)   NULL,
    [EsyaCinsi]              NVARCHAR (50)   NULL,
    [EsyaGtip]               NVARCHAR (12)   NULL,
    [FaturaNo]               NVARCHAR (30)   NULL,
    [FaturaTarih]            DATETIME        NULL,
    [FaturaTutar]            DECIMAL (18, 2) NULL,
    [FaturaDovizKod]         NVARCHAR (3)    NULL,
    [Miktar]                 INT             NULL,
    [OlcuBirimi]             NVARCHAR (5)    NULL,
    [Rejim]                  NVARCHAR (50)   NULL,
    [CikisRejimi]            NVARCHAR (50)   NULL,
    [GidecegiUlke]           NVARCHAR (20)   NULL,
    [MenseUlke]              NVARCHAR (20)   NULL,
    [SozlesmeUlke]           NVARCHAR (20)   NULL,
    [Marka]                  NVARCHAR (50)   NULL,
    [Model]                  NVARCHAR (50)   NULL,
    [UrunKod]                NVARCHAR (50)   NULL,
    [PoNo]                   NVARCHAR (50)   NULL,
    [BeyannameNo]            NVARCHAR (16)   NULL,
    [BeyannameTarihi]        DATETIME        NULL,
    [OlusturmaTarihi]        DATETIME        DEFAULT (getdate()) NOT NULL,
    [GuncellemeTarihi]       DATETIME        NULL,
    [StokGirisDetayId]       INT             NULL,
    CONSTRAINT [PK_ChepStokGirisAktarim] PRIMARY KEY CLUSTERED ([ChepStokGirisAktarimId] ASC)
);

