CREATE TABLE [dbo].[Invoice] (
    [InvoiceId]         UNIQUEIDENTIFIER CONSTRAINT [DF_Invoices_InvoiceId] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [WorkOrderMasterId] UNIQUEIDENTIFIER NOT NULL,
    [SenderNo]          NVARCHAR (30)    NULL,
    [SenderName]        NVARCHAR (250)   NULL,
    [SenderAddress]     NVARCHAR (2000)  NULL,
    [SenderCity]        NVARCHAR (60)    NULL,
    [SenderCountry]     NVARCHAR (25)    NULL,
    [ConsgnNo]          NVARCHAR (30)    NULL,
    [ConsgnName]        NVARCHAR (250)   NULL,
    [ConsgnAddress]     NVARCHAR (2000)  NULL,
    [ConsgnCity]        NVARCHAR (60)    NULL,
    [ConsgnCountry]     NVARCHAR (25)    NULL,
    [TransptrName]      NVARCHAR (250)   NULL,
    [VesselName]        NVARCHAR (250)   NULL,
    [AgentName]         NVARCHAR (250)   NULL,
    [PlateNo]           NVARCHAR (500)   NULL,
    [AwbNo]             NVARCHAR (30)    NULL,
    [BLNo]              NVARCHAR (25)    NULL,
    [Incoterms]         NVARCHAR (25)    NULL,
    [DeliveryLocation]  NVARCHAR (250)   NULL,
    [InvoiceAmount]     DECIMAL (18, 2)  NOT NULL,
    [InvoiceCurrency]   NVARCHAR (6)     NOT NULL,
    [FreightAmount]     DECIMAL (18, 2)  NULL,
    [FreightCurrency]   NVARCHAR (6)     NULL,
    [InsuranceAmount]   DECIMAL (18, 2)  NULL,
    [InsuranceCurrency] NVARCHAR (6)     NULL,
    [CreatedDate]       DATETIME         CONSTRAINT [DF_Invoice_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [ContainerNo]       NVARCHAR (MAX)   NULL,
    [GtbReferenceNo]    NVARCHAR (25)    NULL,
    [PaymentMethod]     NVARCHAR (50)    NULL,
    [EntryExitCustoms]  NVARCHAR (250)   NULL,
    [Customs]           NVARCHAR (250)   NULL,
    CONSTRAINT [PK_Invoices] PRIMARY KEY CLUSTERED ([InvoiceId] ASC),
    CONSTRAINT [FK_Invoice_WorkOrderMaster] FOREIGN KEY ([WorkOrderMasterId]) REFERENCES [dbo].[WorkOrderMaster] ([WorkOrderMasterId]),
    CONSTRAINT [FK_Invoices_Invoices] FOREIGN KEY ([InvoiceId]) REFERENCES [dbo].[Invoice] ([InvoiceId])
);



