CREATE TABLE [dbo].[Teminat] (
    [TeminatId]             INT             IDENTITY (1, 1) NOT NULL,
    [TeminatTipiId]         INT             NOT NULL,
    [DurumId]               INT             NOT NULL,
    [DosyaTipi]             VARCHAR (250)   NULL,
    [DosyaNo]               VARCHAR (50)    NULL,
    [Gonderici]             VARCHAR (250)   NULL,
    [Alici]                 VARCHAR (250)   NULL,
    [TescilNo]              VARCHAR (50)    NULL,
    [TescilTarihi]          DATETIME        NULL,
    [Gumruk]                VARCHAR (250)   NULL,
    [Banka]                 VARCHAR (250)   NULL,
    [AntrepoKodu]           VARCHAR (50)    NULL,
    [TeminatRefNo]          VARCHAR (50)    NULL,
    [TeminatTutari]         DECIMAL (18, 2) NULL,
    [OdenecekTutar]         DECIMAL (18, 2) NULL,
    [MuracatNo]             VARCHAR (50)    NULL,
    [MuracatTarihi]         DATETIME        NULL,
    [CozumTarihi]           DATETIME        NULL,
    [Aciklama]              VARCHAR (250)   NULL,
    [EvrakTeslimAlan]       VARCHAR (50)    NULL,
    [EvrakTeslimAlmaTarihi] DATETIME        NULL,
    [EvrakTeslimEden]       VARCHAR (50)    NULL,
    [EvrakTeslimTarihi]     DATETIME        NULL,
    [InsDate]               DATETIME        CONSTRAINT [DF_Teminat_InsDate] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_Teminat] PRIMARY KEY CLUSTERED ([TeminatId] ASC)
);

